### ISSUE TITLE
Ensure notebooks work with latest h2o (3.20.0.5)

### ISSUE THREAD

**Issue by navdeep-G** [h2oai/mli-resources#5]
* Shouldn't be an issue, but just to double check.

**Comment by jphall663** [comment]
On my last docker build I saw: 
> Step 11/16 : RUN pip uninstall h2o || true &&     pip install -f http://h2o-release.s3.amazonaws.com/h2o/rel-wright/4/Python/h2o-3.20.0.4-py2.py3-none-any.whl --trusted-host h2o-release.s3.amazonaws.com h2o

That's a pretty recent version. 

Closing for now.
